/*
 * SPDX-FileCopyrightText: 2025 IObundle, Lda
 *
 * SPDX-License-Identifier: MIT
 *
 * Py2HWSW Version 0.81 has generated this code (https://github.com/IObundle/py2hwsw).
 */

#ifndef H_IOB_CACHE_AXI_CSRS_CSRS_H
#define H_IOB_CACHE_AXI_CSRS_CSRS_H

/** @file iob_cache_axi_csrs.h
 *  @brief Function prototypes for the iob_cache_axi core.
 *
 *  This file contains the function prototypes to access the Control and Status
 * Registers (CSRs) for the iob_cache_axi core.
 *
 *  This file is automatically generated by Py2HWSW
 */

#include <stdint.h>

// used address space width
/**
 * @def IOB_CACHE_AXI_CSRS_CSRS_ADDR_W
 * @brief Used core address space width.
 *
 * This macro defines the required address width in bits to access all core
 * CSRs.
 */
#define IOB_CACHE_AXI_CSRS_CSRS_ADDR_W 5

// Addresses
/**
 * @def IOB_CACHE_AXI_CSRS_WTB_EMPTY_ADDR
 * @brief WTB_EMPTY CSR address.
 */
#define IOB_CACHE_AXI_CSRS_WTB_EMPTY_ADDR 0
/**
 * @def IOB_CACHE_AXI_CSRS_WTB_FULL_ADDR
 * @brief WTB_FULL CSR address.
 */
#define IOB_CACHE_AXI_CSRS_WTB_FULL_ADDR 1
/**
 * @def IOB_CACHE_AXI_CSRS_RW_HIT_ADDR
 * @brief RW_HIT CSR address.
 */
#define IOB_CACHE_AXI_CSRS_RW_HIT_ADDR 4
/**
 * @def IOB_CACHE_AXI_CSRS_RW_MISS_ADDR
 * @brief RW_MISS CSR address.
 */
#define IOB_CACHE_AXI_CSRS_RW_MISS_ADDR 8
/**
 * @def IOB_CACHE_AXI_CSRS_READ_HIT_ADDR
 * @brief READ_HIT CSR address.
 */
#define IOB_CACHE_AXI_CSRS_READ_HIT_ADDR 12
/**
 * @def IOB_CACHE_AXI_CSRS_READ_MISS_ADDR
 * @brief READ_MISS CSR address.
 */
#define IOB_CACHE_AXI_CSRS_READ_MISS_ADDR 16
/**
 * @def IOB_CACHE_AXI_CSRS_WRITE_HIT_ADDR
 * @brief WRITE_HIT CSR address.
 */
#define IOB_CACHE_AXI_CSRS_WRITE_HIT_ADDR 20
/**
 * @def IOB_CACHE_AXI_CSRS_WRITE_MISS_ADDR
 * @brief WRITE_MISS CSR address.
 */
#define IOB_CACHE_AXI_CSRS_WRITE_MISS_ADDR 24
/**
 * @def IOB_CACHE_AXI_CSRS_RST_CNTRS_ADDR
 * @brief RST_CNTRS CSR address.
 */
#define IOB_CACHE_AXI_CSRS_RST_CNTRS_ADDR 28
/**
 * @def IOB_CACHE_AXI_CSRS_INVALIDATE_ADDR
 * @brief INVALIDATE CSR address.
 */
#define IOB_CACHE_AXI_CSRS_INVALIDATE_ADDR 29
/**
 * @def IOB_CACHE_AXI_CSRS_VERSION_ADDR
 * @brief version CSR address.
 */
#define IOB_CACHE_AXI_CSRS_VERSION_ADDR 30

// Data widths (bit)
/**
 * @def IOB_CACHE_AXI_CSRS_WTB_EMPTY_W
 * @brief WTB_EMPTY CSR Width.
 */
#define IOB_CACHE_AXI_CSRS_WTB_EMPTY_W 8
/**
 * @def IOB_CACHE_AXI_CSRS_WTB_FULL_W
 * @brief WTB_FULL CSR Width.
 */
#define IOB_CACHE_AXI_CSRS_WTB_FULL_W 8
/**
 * @def IOB_CACHE_AXI_CSRS_RW_HIT_W
 * @brief RW_HIT CSR Width.
 */
#define IOB_CACHE_AXI_CSRS_RW_HIT_W 32
/**
 * @def IOB_CACHE_AXI_CSRS_RW_MISS_W
 * @brief RW_MISS CSR Width.
 */
#define IOB_CACHE_AXI_CSRS_RW_MISS_W 32
/**
 * @def IOB_CACHE_AXI_CSRS_READ_HIT_W
 * @brief READ_HIT CSR Width.
 */
#define IOB_CACHE_AXI_CSRS_READ_HIT_W 32
/**
 * @def IOB_CACHE_AXI_CSRS_READ_MISS_W
 * @brief READ_MISS CSR Width.
 */
#define IOB_CACHE_AXI_CSRS_READ_MISS_W 32
/**
 * @def IOB_CACHE_AXI_CSRS_WRITE_HIT_W
 * @brief WRITE_HIT CSR Width.
 */
#define IOB_CACHE_AXI_CSRS_WRITE_HIT_W 32
/**
 * @def IOB_CACHE_AXI_CSRS_WRITE_MISS_W
 * @brief WRITE_MISS CSR Width.
 */
#define IOB_CACHE_AXI_CSRS_WRITE_MISS_W 32
/**
 * @def IOB_CACHE_AXI_CSRS_RST_CNTRS_W
 * @brief RST_CNTRS CSR Width.
 */
#define IOB_CACHE_AXI_CSRS_RST_CNTRS_W 8
/**
 * @def IOB_CACHE_AXI_CSRS_INVALIDATE_W
 * @brief INVALIDATE CSR Width.
 */
#define IOB_CACHE_AXI_CSRS_INVALIDATE_W 8
/**
 * @def IOB_CACHE_AXI_CSRS_VERSION_W
 * @brief version CSR Width.
 */
#define IOB_CACHE_AXI_CSRS_VERSION_W 16

// Base Address
/**
 * @brief Set core base address.
 *
 * This function sets the base address for the core in the system. All other
 * accesses are offset from this base address.
 *
 * @param addr Base address for core.
 */
void iob_cache_axi_csrs_init_baseaddr(uint32_t addr);

// IO read and write function prototypes
/**
 * @brief Write access function prototype.
 *
 * @param addr Address to write to.
 * @param data_w Data width in bits.
 * @param value Value to write.
 */
void iob_write(uint32_t addr, uint32_t data_w, uint32_t value);
/**
 * @brief Read access function prototype.
 *
 * @param addr Address to write to.
 * @param data_w Data width in bits.
 * @return uint32_t Read data value.
 */
uint32_t iob_read(uint32_t addr, uint32_t data_w);

// Core Setters and Getters
/**
 * @brief Get WTB_EMPTY value.
 * Write-through buffer empty (1) or non-empty (0).
 * @return uint8_t WTB_EMPTY value.
 */
uint8_t iob_cache_axi_csrs_get_WTB_EMPTY();
/**
 * @brief Get WTB_FULL value.
 * Write-through buffer full (1) or non-full (0).
 * @return uint8_t WTB_FULL value.
 */
uint8_t iob_cache_axi_csrs_get_WTB_FULL();
/**
 * @brief Get RW_HIT value.
 * Read and write hit counter.
 * @return uint32_t RW_HIT value.
 */
uint32_t iob_cache_axi_csrs_get_RW_HIT();
/**
 * @brief Get RW_MISS value.
 * Read and write miss counter.
 * @return uint32_t RW_MISS value.
 */
uint32_t iob_cache_axi_csrs_get_RW_MISS();
/**
 * @brief Get READ_HIT value.
 * Read hit counter.
 * @return uint32_t READ_HIT value.
 */
uint32_t iob_cache_axi_csrs_get_READ_HIT();
/**
 * @brief Get READ_MISS value.
 * Read miss counter.
 * @return uint32_t READ_MISS value.
 */
uint32_t iob_cache_axi_csrs_get_READ_MISS();
/**
 * @brief Get WRITE_HIT value.
 * Write hit counter.
 * @return uint32_t WRITE_HIT value.
 */
uint32_t iob_cache_axi_csrs_get_WRITE_HIT();
/**
 * @brief Get WRITE_MISS value.
 * Write miss counter.
 * @return uint32_t WRITE_MISS value.
 */
uint32_t iob_cache_axi_csrs_get_WRITE_MISS();
/**
 * @brief Set RST_CNTRS value.
 * Reset read/write hit/miss counters by writing any value to this register.
 * @param value RST_CNTRS Value.
 */
void iob_cache_axi_csrs_set_RST_CNTRS(uint8_t value);
/**
 * @brief Set INVALIDATE value.
 * Invalidate the cache data contents by writing any value to this register.
 * @param value INVALIDATE Value.
 */
void iob_cache_axi_csrs_set_INVALIDATE(uint8_t value);
/**
 * @brief Get version value.
 * Product version. This 16-bit register uses nibbles to represent decimal
 * numbers using their binary values. The two most significant nibbles represent
 * the integral part of the version, and the two least significant nibbles
 * represent the decimal part. For example V12.34 is represented by 0x1234.
 * @return uint16_t version value.
 */
uint16_t iob_cache_axi_csrs_get_version();

#endif // H_IOB_CACHE_AXI_CSRS__CSRS_H
