/*
 * SPDX-FileCopyrightText: 2026 IObundle, Lda
 *
 * SPDX-License-Identifier: MIT
 *
 * Py2HWSW Version 0.81.0 has generated this code (https://github.com/IObundle/py2hwsw).
 */

#ifndef H_IOB_CACHE_BACK_END_AXI_CONF_H
#define H_IOB_CACHE_BACK_END_AXI_CONF_H

#define IOB_CACHE_BACK_END_AXI_FE_ADDR_W 24
#define IOB_CACHE_BACK_END_AXI_FE_DATA_W 32
#define IOB_CACHE_BACK_END_AXI_BE_ADDR_W 24
#define IOB_CACHE_BACK_END_AXI_BE_DATA_W 32
#define IOB_CACHE_BACK_END_AXI_WORD_OFFSET_W 3
#define IOB_CACHE_BACK_END_AXI_WRITE_POL 0
#define IOB_CACHE_BACK_END_AXI_AXI_ID_W 1
#define IOB_CACHE_BACK_END_AXI_AXI_ID 0
#define IOB_CACHE_BACK_END_AXI_AXI_LEN_W 4
#define IOB_CACHE_BACK_END_AXI_AXI_ADDR_W BE_ADDR_W
#define IOB_CACHE_BACK_END_AXI_AXI_DATA_W BE_DATA_W
#define IOB_CACHE_BACK_END_AXI_FE_NBYTES FE_DATA_W / 8
#define IOB_CACHE_BACK_END_AXI_FE_NBYTES_W $clog2(FE_NBYTES)
#define IOB_CACHE_BACK_END_AXI_BE_NBYTES BE_DATA_W / 8
#define IOB_CACHE_BACK_END_AXI_BE_NBYTES_W $clog2(BE_NBYTES)
#define IOB_CACHE_BACK_END_AXI_LINE2BE_W                                       \
  WORD_OFFSET_W - $clog2(BE_DATA_W / FE_DATA_W)
#define IOB_CACHE_BACK_END_AXI_VERSION 0x008100

#endif // H_IOB_CACHE_BACK_END_AXI_CONF_H
